# NumPy








In [ ]:
import numpy as np


In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
np.array([1,2,3,],dtype=float)

array([1., 2., 3.])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11).reshape(5,2) #means 5 rows and 2 coloumns


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3,4))

array([[0.80097809, 0.26766344, 0.73060583, 0.84935664],
       [0.27317555, 0.08646857, 0.78728098, 0.75937867],
       [0.83459131, 0.98426712, 0.86946792, 0.5920386 ]])

In [ ]:
np.linspace(-10,10,10) # lower range, upper range, number of items you want to generate

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# NumPy array


In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
a1.ndim # it says number of dimension

1

In [ ]:
a2.shape

(3, 4)

In [ ]:
a2.size # it says number of items

12

In [ ]:
a2.itemsize # it says size of items

8

In [ ]:
print(a1.dtype)
print(a2.dtype) # ignore 64

int64
float64


# changing datatype

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# scalar operations
print(a1*2)
print(a1+2)
print(a1-2)
print(a1/2)
print(a1**2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [ ]:
# relational
print(a2>15)
print(a2==15)


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False  True]
 [False False False False]
 [False False False False]]


In [ ]:
# vector operations
print(a1*a2)
print(a1+a2)
print(a1-a2)
print(a1/a2)
print(a1**a2)

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]


# array functions





In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)
print(a2)

[[83. 31. 22.]
 [86. 12. 98.]
 [19. 85. 98.]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
#max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1)) # sum of all
print(np.prod(a1)) # product of all

98.0
12.0
534.0
906080621920320.0


In [ ]:
np.max(a1,axis=0) # row wise # 0 means coloumns 1 means row

array([86., 85., 98.])

In [ ]:
#mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

59.333333333333336
83.0
34.934860017530404
1220.4444444444446


In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)  # 3*4 * 4*3 = 3*3
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponent
np.log(a1)

array([[4.41884061, 3.4339872 , 3.09104245],
       [4.4543473 , 2.48490665, 4.58496748],
       [2.94443898, 4.44265126, 4.58496748]])

In [ ]:
print(np.round(np.random.random((2,3))*100)) # round off to nearest integer
print(np.floor(np.random.random((2,3))*100)) # previous integer
print(np.ceil(np.random.random((2,3))*100)) # next integer

[[55.  2. 65.]
 [20. 21. 13.]]
[[ 6. 39. 29.]
 [ 8. 41. 73.]]
[[ 9.  2. 43.]
 [68. 20.  8.]]


# Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)


[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
a1[-1]


np.int64(9)

In [ ]:
a2[1,2] #row,coloumn

np.int64(6)

In [ ]:
a3[1,0,1]

np.int64(5)

In [ ]:
# slicing
a1[2:5]

array([2, 3, 4])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[0:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[0::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,0::3]

array([4, 7])

In [ ]:
a2[0:2,1:5]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[:3:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):  # converting in 1d
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [ ]:
#transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.ravel() # 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [ ]:
# horizontal
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#vertical
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spiliting

In [ ]:
# horizontal
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]